---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - java
  - package-ecosystem: maven
    directory: "/logging"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/utils"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/testing"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/queue"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/model"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/validation"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - govuk-pay
      - github_actions
