---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - java
  - package-ecosystem: maven
    directory: "/logging-dropwizard-3"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "org.dhatim:dropwizard-sentry"
        # We essentially forked Dropwizard Sentry because it did not support
        # Dropwizard 3.x — there is now a Dropwizard Sentry 4.x, which supports
        # Dropwizard 4.x (and maybe Dropwizard 3.x), but we’d need to do work
        # to go back to using an unmodified version
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
  - package-ecosystem: maven
    directory: "/utils"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "org.eclipse.persistence:org.eclipse.persistence.jpa"
        # We use EclipseLink 2.7.x in our Java microservices
        versions:
          - ">= 3"
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
  - package-ecosystem: maven
    directory: "/testing"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
  - package-ecosystem: maven
    directory: "/queue"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
  - package-ecosystem: maven
    directory: "/model"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # Dropwizard 4.x only works with Jakarta EE and not Java EE
        versions:
          - ">= 4"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # dropwizard-testing-junit4 4.x only works with Dropwizard 4.x
        versions:
          - ">= 4"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - govuk-pay
      - github_actions
