---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # We don't want to upgrade to Dropwizard 5.x just yet
        versions:
          - ">= 5"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # We don't want to upgrade to Dropwizard 5.x just yet
        versions:
          - ">= 5"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - java
  - package-ecosystem: maven
    directory: "/logging-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/utils-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/testing-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/queue-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/model-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/validation-dropwizard-4"
    schedule:
      interval: weekly
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - govuk-pay
      - github_actions
