name: Check GPG Signing Key Expiration

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  check-signing-key:
    runs-on: ubuntu-latest
    steps:
      - name: Check Signing Key Expiry
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo
          echo "Checking signing key for expiration"

          # See https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob_plain;f=doc/DETAILS for details of all the columns
          SECRET_KEY_DETAILS=$(gpg --with-colons --fixed-list-mode --show-keys <<<"$GPG_PRIVATE_KEY" | grep "^sec:")
          SECRET_KEY_VALIDITY=$(cut -f "2" -d ":" <<< "$SECRET_KEY_DETAILS")
          SECRET_KEY_EXPIRATION_TIMESTAMP=$(cut -f "7" -d ":" <<< "$SECRET_KEY_DETAILS")

          if [ "$(uname)" == "Darwin" ]; then
            SECRET_KEY_EXPIRATION_DATE=$(date -j -f "%s" "$SECRET_KEY_EXPIRATION_TIMESTAMP")
          else
            SECRET_KEY_EXPIRATION_DATE=$(date -d "@${SECRET_KEY_EXPIRATION_TIMESTAMP}")
          fi

          if [[ "$SECRET_KEY_VALIDITY" == "e" ]]; then
              echo "Key has expired!"
              echo

              echo "Key expired on $SECRET_KEY_EXPIRATION_DATE"
              echo
              echo "See https://pay-team-manual.cloudapps.digital/manual/credential-management/rotate-maven-signing-key.html for help extending/rotating the key"
              exit 1
          fi

          echo
          echo "Key does not expire until $SECRET_KEY_EXPIRATION_DATE"
