name: Release to maven
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Install Java and Maven
        uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set package version
        run: |
          mvn versions:set -DnewVersion="1.0.$(date +"%Y%m%d%H%M%S")"
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@9001e5ada637a021e98c752a0b292c01151378b5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          server_id: ossrh
