name: Release to maven
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install Java and Maven
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set package version
        run: |
          mvn versions:set -DnewVersion="1.0.$(date +"%Y%m%d%H%M%S")"
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@9001e5ada637a021e98c752a0b292c01151378b5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          server_id: ossrh
